SELECT * FROM langhillherd.milk_comp;
update langhillherd.milk_comp set SAMPLED_DATE = STR_TO_DATE(SAMPLED_DATE,'%d/%m/%Y');
update langhillherd.milk_comp set SAMPLED_DATE_MON = STR_TO_DATE(SAMPLED_DATE_MON,'%d/%m/%Y');
update langhillherd.milk_comp set SAMPLED_DATE_TUE = STR_TO_DATE(SAMPLED_DATE_TUE,'%d/%m/%Y');
update langhillherd.milk_comp set SAMPLED_DATE_WED = STR_TO_DATE(SAMPLED_DATE_WED,'%d/%m/%Y');
update langhillherd.milk_comp set SAMPLED_DATE_THU = STR_TO_DATE(SAMPLED_DATE_THU,'%d/%m/%Y');
update langhillherd.milk_comp set SAMPLED_DATE_FRI = STR_TO_DATE(SAMPLED_DATE_FRI,'%d/%m/%Y');

create table milk_comp_mon;

create table milk_comp_mon select MC_EAR_TAG, MC_LACT_NO, SAMPLED_DATE, MC_FEED_GROUP, YIELD_1, FAT_PERCENTAGE_1, PROTEIN_PERCENTAGE_1, CELL_COUNT_1, 
YIELD_2, FAT_PERCENTAGE_2, PROTEIN_PERCENTAGE_2, CELL_COUNT_2, 
YIELD_3, FAT_PERCENTAGE_3, PROTEIN_PERCENTAGE_3, CELL_COUNT_3, 
STDYIELD,	AVGYIELD,	STDFATPERC,	AVGFATPERC,	STDPROTEINPERC,	AVGPROTEINPERC,	STDCELLCOUNT,	AVGCELLCOUNT,	
SAMPLED_DATE_MON
FROM langhillherd.milk_comp
group by milk_comp.SAMPLED_DATE_MON, milk_comp.MC_EAR_TAG;

create table milk_comp_tue select MC_EAR_TAG, MC_LACT_NO, SAMPLED_DATE, MC_FEED_GROUP, YIELD_1, FAT_PERCENTAGE_1, PROTEIN_PERCENTAGE_1, CELL_COUNT_1, YIELD_2, FAT_PERCENTAGE_2, PROTEIN_PERCENTAGE_2, CELL_COUNT_2, YIELD_3, FAT_PERCENTAGE_3, PROTEIN_PERCENTAGE_3, CELL_COUNT_3,
STDYIELD,	AVGYIELD,	STDFATPERC,	AVGFATPERC,	STDPROTEINPERC,	AVGPROTEINPERC,	STDCELLCOUNT,	AVGCELLCOUNT,	
 SAMPLED_DATE_TUE
FROM langhillherd.milk_comp
group by milk_comp.SAMPLED_DATE_TUE, milk_comp.MC_EAR_TAG;

create table milk_comp_wed select MC_EAR_TAG, MC_LACT_NO, SAMPLED_DATE, MC_FEED_GROUP, YIELD_1, FAT_PERCENTAGE_1, PROTEIN_PERCENTAGE_1, CELL_COUNT_1, YIELD_2, FAT_PERCENTAGE_2, PROTEIN_PERCENTAGE_2, CELL_COUNT_2, YIELD_3, FAT_PERCENTAGE_3, PROTEIN_PERCENTAGE_3, CELL_COUNT_3, STDYIELD,	AVGYIELD,	STDFATPERC,	AVGFATPERC,	STDPROTEINPERC,	AVGPROTEINPERC,	STDCELLCOUNT,	AVGCELLCOUNT,	SAMPLED_DATE_WED
FROM langhillherd.milk_comp
group by milk_comp.SAMPLED_DATE_WED, milk_comp.MC_EAR_TAG;

create table milk_comp_thu select MC_EAR_TAG, MC_LACT_NO, SAMPLED_DATE, MC_FEED_GROUP, YIELD_1, FAT_PERCENTAGE_1, PROTEIN_PERCENTAGE_1, CELL_COUNT_1, YIELD_2, FAT_PERCENTAGE_2, PROTEIN_PERCENTAGE_2, CELL_COUNT_2, YIELD_3, FAT_PERCENTAGE_3, PROTEIN_PERCENTAGE_3, CELL_COUNT_3,STDYIELD,	AVGYIELD,	STDFATPERC,	AVGFATPERC,	STDPROTEINPERC,	AVGPROTEINPERC,	STDCELLCOUNT,	AVGCELLCOUNT,	 SAMPLED_DATE_THU
FROM langhillherd.milk_comp
group by milk_comp.SAMPLED_DATE_THU, milk_comp.MC_EAR_TAG;

create table milk_comp_fri select MC_EAR_TAG, MC_LACT_NO, SAMPLED_DATE, MC_FEED_GROUP, YIELD_1, FAT_PERCENTAGE_1, PROTEIN_PERCENTAGE_1, CELL_COUNT_1, YIELD_2, FAT_PERCENTAGE_2, PROTEIN_PERCENTAGE_2, CELL_COUNT_2, YIELD_3, FAT_PERCENTAGE_3, PROTEIN_PERCENTAGE_3, CELL_COUNT_3, STDYIELD,	AVGYIELD,	STDFATPERC,	AVGFATPERC,	STDPROTEINPERC,	AVGPROTEINPERC,	STDCELLCOUNT,	AVGCELLCOUNT,	SAMPLED_DATE_FRI
FROM langhillherd.milk_comp
group by milk_comp.SAMPLED_DATE_FRI, milk_comp.MC_EAR_TAG;